### ISSUE TITLE
plants lines 33-36

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-world-marleyhaupt1#1]
Hi Will,

Sorry to bug you over Spring Break. I have been working on the RWorld homework and for some reason I can't get my plants to initiate across my terrain. I think there is a problem somewhere in my init.plants function on lines 33-36. I have tried looping through the rows and columns to initiate plants, but for some reason it isn't populating the array with plant names.

Do you see any super obvious problems that I am missing?

Thanks,
Marley

**Comment by willpearse** [comment]
Ah - this is an easy one to miss, because it "looks" right even though it's wrong. It took me a minute, to be honest, so don't feel bad about this one. You also got it down to the right lines, and the structure of what you're writing is very good. You clearly understand the "story" of the code, because it's well laid-out etc.

What's the difference between ```for(i in ncol(matrix))``` and ```for(i in 1:ncol(matrix))```?

**Comment by marleyhaupt1** [comment]
Oh my word. I figured it was probably something stupid like that! Thanks Will

**Comment by willpearse** [comment]
No worries. It's a good sign you're making "stupid" mistakes; this means
you're beginning to take the "simple" things for granted. Your coding style
is really coming along - well done!
